### ISSUE TITLE
User issue

### ISSUE THREAD

**Issue by insxa** [orwah/Simple-Info-AddOn-for-VestaCP#2]
When user login i get:
Internal vesta error

**Comment by orwah** [comment]
1- 
check the "owner" for uploaded files , must be like any other vesta file:  **root:root**
only info.txt owner is admin:admin (so apache can write on it).

2- 
it's tested on Updated vesta version only : Vesta 0.9.8-16
do you have Updated vesta ?

3-  
maybe your version of "panel.html" is differint , 
you can use the original ones , Just add :

```
           <div class="l-stat__col <?php if($TAB == 'INFO' ) echo 'l-stat__col--active' ?>">
          <a href="/list/info/admin.php">
            <div class="l-stat__col-title"><?=__('INFO')?></div>
            <ul>
              <li></li>
            </ul>
          </a>
        </div>
```

you can put it after the BACKUP tab code for admin/panel.html 
Backup tab cod is : 

```
    <div class="l-stat__col <?php if($TAB == 'BACKUP' ) echo 'l-stat__col--active' ?>">
          <a href="/list/backup/">
            <div class="l-stat__col-title"><?=__('BACKUP')?></div>
            <ul>
              <li><?=__('backups')?>: <span><?=$panel[$user]['U_BACKUPS']?></span></li>
            </ul>
          </a>
        </div>
```

and put it befor the USER tab in user/panel.html 

regards
